name = "protoboard"
layers = ["terrain", "units"]
prefix = "../protoboard/assets"

[tiles]
defender = "shield.png"
archer = "bow.png"
warrior = "sword.png"
raccoon = "raccoon.png"

mountains = "mountains.png"
woods = "woods.png"
